apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: myapp
          image: ${REPO}:${VERSION}
          ports:
            - name: web
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-seb
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: web
      port: 80
      targetPort: 8080
