apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: my-app
          image: ${REPO}:${VERSION}
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 50Mi
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - name: web
      port: 80
      targetPort: 8080
